"use client";

import { useEffect, useState, type FormEvent } from "react";
import NextImage, { type ImageProps } from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronLeft, ChevronRight, Camera, Menu, X, Share2, Layers3, ScanLine, Maximize2, ShieldCheck, MessageCircle } from "lucide-react";
import type { Project } from "@/db/schema";
import { categoryLabels, type Category } from "@/lib/categories";

const services = [
  { num: "01", icon: ScanLine, title: "Architectural Glass", desc: "Glass partitions, shower enclosures, mirrors and refined details that invite light into every space." },
  { num: "02", icon: Layers3, title: "Aluminum Systems", desc: "Precision-built doors and windows with slim profiles, effortless function and enduring beauty." },
  { num: "03", icon: Maximize2, title: "Exterior Facades", desc: "Striking elevations and curtain walls designed to make a lasting architectural statement." },
  { num: "04", icon: ShieldCheck, title: "Interiors & Furnishing", desc: "Finishing touches and decorative hardware that bring your vision together, beautifully." },
];
const filters = ["All Projects", "INTERIOR", "EXTERIOR", "GLASS_WORK", "ALUMINIUM_DOORS_WINDOWS", "HOME_FURNISHING"] as const;
type Filter = typeof filters[number];

function Logo({ compact = false }: { compact?: boolean }) {
  return <a href="#top" className={`brand ${compact ? "brand-compact" : ""}`} aria-label="Jauhar Decor - back to top"><Image src="/logo-jauhar.svg" alt="Jauhar Decor Home Furnishing logo" width={150} height={120} priority unoptimized /></a>;
}

function QuoteModal({ onClose }: { onClose: () => void }) {
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; window.addEventListener("keydown", key); return () => { document.body.style.overflow = previous; window.removeEventListener("keydown", key); }; }, [onClose]);
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setSending(true); setError("");
    const form = new FormData(e.currentTarget);
    try {
      const res = await fetch("/api/quotes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) });
      if (!res.ok) throw new Error("Unable to send. Please try again.");
      setSent(true);
    } catch (err) { setError(err instanceof Error ? err.message : "Something went wrong."); }
    finally { setSending(false); }
  }
  return <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose} role="presentation"><motion.div className="quote-modal" initial={{ y: 24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 24, opacity: 0 }} onMouseDown={e => e.stopPropagation()} role="dialog" aria-modal="true" aria-label="Request a quotation"><button className="modal-close" onClick={onClose} aria-label="Close quotation form"><X size={20}/></button>{sent ? <div className="quote-success"><span className="success-icon"><Check size={28}/></span><span className="eyebrow">REQUEST RECEIVED</span><h2>Thank you for reaching out.</h2><p>We&apos;ve received your project details. Our team will be in touch to explore what we can create together.</p><button className="button button-light" onClick={onClose}>Close <ArrowUpRight size={17}/></button></div> : <><span className="eyebrow">LET&apos;S BUILD SOMETHING EXCEPTIONAL</span><h2>Tell us about<br/><em>your vision.</em></h2><p className="modal-intro">Share a few details and we&apos;ll get back to you with a tailored consultation.</p><form onSubmit={submit} className="quote-form"><div className="form-row"><label>Your name <input name="name" placeholder="Full name" required maxLength={100}/></label><label>Email address <input name="email" type="email" placeholder="you@example.com" required/></label></div><div className="form-row"><label>Phone number <input name="phone" type="tel" placeholder="Your phone number" required/></label><label>Interested in <select name="service" required defaultValue=""><option value="" disabled>Select a service</option><option>Architectural Glass</option><option>Aluminum Systems</option><option>Exterior Facades</option><option>Interiors & Furnishing</option><option>Other</option></select></label></div><label>Project details <textarea name="message" rows={3} placeholder="A little about your project, timeline, or ideas..."/></label>{error && <p className="form-error">{error}</p>}<button className="button button-light submit-button" disabled={sending}>{sending ? "Sending..." : "Send inquiry"}<ArrowUpRight size={18}/></button></form></>}</motion.div></motion.div>;
}

function ProjectLightbox({ project, onClose }: { project: Project; onClose: () => void }) {
  const images = project.gallery?.length ? project.gallery : [project.coverImage];
  const [index, setIndex] = useState(0);
  const [compare, setCompare] = useState(false);
  const [position, setPosition] = useState(50);
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); if (e.key === "ArrowRight") setIndex(i => (i + 1) % images.length); if (e.key === "ArrowLeft") setIndex(i => (i - 1 + images.length) % images.length); }; window.addEventListener("keydown", key); return () => { document.body.style.overflow = old; window.removeEventListener("keydown", key); }; }, [onClose, images.length]);
  return <motion.div className="lightbox" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} role="dialog" aria-modal="true" aria-label={project.title}><div className="lightbox-top"><Logo compact/><span>PROJECT / {categoryLabels[project.category as Category]}</span><button onClick={onClose} aria-label="Close project"><X size={24}/></button></div><div className="lightbox-image-area"><div className="lightbox-image"><ProjectArtwork src={images[index]} alt={`${project.title} view ${index + 1}`} sizes="100vw" className="object-cover"/>{compare && images.length > 1 && <div className="compare-overlay" style={{ width: `${position}%` }}><ProjectArtwork src={images[(index + 1) % images.length]} alt="Alternate project view" sizes="100vw" className="compare-img"/><span className="compare-line"/></div>}{compare && images.length > 1 && <input className="compare-range" type="range" min="0" max="100" value={position} onChange={e => setPosition(Number(e.target.value))} aria-label="Compare project views"/>}</div>{images.length > 1 && !compare && <><button className="gallery-arrow left" onClick={() => setIndex((index - 1 + images.length) % images.length)} aria-label="Previous image"><ChevronLeft/></button><button className="gallery-arrow right" onClick={() => setIndex((index + 1) % images.length)} aria-label="Next image"><ChevronRight/></button></>}</div><div className="lightbox-bottom"><div><span className="eyebrow">{project.location || "JAUHAR DECOR PROJECT"} <span className="sep">/</span> {project.completedAt ? new Date(project.completedAt).getFullYear() : "RECENT WORK"}</span><h2>{project.title}</h2><p>{project.description}</p></div><div className="lightbox-actions">{images.length > 1 && <button onClick={() => setCompare(!compare)} className="compare-button">{compare ? "View gallery" : "Compare views"} <span>{compare ? <X size={16}/> : <Maximize2 size={16}/>}</span></button>}<span className="image-count">{String(index + 1).padStart(2, "0")} / {String(images.length).padStart(2, "0")}</span></div></div></motion.div>;
}

const heroImage = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop";
const detailImage = "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop";
const comparisonBefore = "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1600&auto=format&fit=crop";
const comparisonAfter = heroImage;

function Image(props: ImageProps) {
  const localPhotoSources: Record<string, string> = {
    "/images/hero-editorial.jpg": heroImage,
    "/images/project-studio.jpg": detailImage,
  };
  const src = typeof props.src === "string" ? localPhotoSources[props.src] || props.src : props.src;
  const className = typeof props.src === "string" && localPhotoSources[props.src]
    ? `${props.className || ""} object-cover w-full h-full`
    : props.className;
  return <NextImage {...props} src={src} className={className} onError={event => {
    props.onError?.(event);
    if (props.onError) return;
    if (event.currentTarget.dataset.fallbackAttempted) { event.currentTarget.style.visibility = "hidden"; return; }
    event.currentTarget.dataset.fallbackAttempted = "true";
    event.currentTarget.srcset = "";
    event.currentTarget.src = src === heroImage ? detailImage : heroImage;
  }} />;
}

function BeforeAfterSlider() {
  const [position, setPosition] = useState(50);
  return <section className="before-after-section" aria-labelledby="before-after-title"><div className="before-after-inner content-width"><div className="section-kicker"><span className="section-dot"/> A TRANSFORMATION, IN DETAIL <span className="section-number">04 / 04</span></div><div className="before-after-heading"><div><h2 id="before-after-title">A different<br/><em>perspective.</em></h2></div><p>See what a thoughtful frame, a clear view, and considered craftsmanship can do for a space.</p></div><div className="before-after-frame"><div className="before-after-base"><Image src={comparisonBefore} alt="Interior before architectural glass and aluminum detailing" fill sizes="(max-width: 800px) 100vw, 84vw"/></div><div className="before-after-overlay" style={{ clipPath: `inset(0 ${100 - position}% 0 0)` }}><Image src={comparisonAfter} alt="Finished residence with refined glass and aluminum detailing" fill sizes="(max-width: 800px) 100vw, 84vw"/></div><span className="before-after-label before-label">BEFORE</span><span className="before-after-label after-label">AFTER</span><div className="before-after-divider" style={{ left: `${position}%` }} aria-hidden="true"><span><ChevronLeft size={15}/><ChevronRight size={15}/></span></div><input className="before-after-range" type="range" min="0" max="100" value={position} onChange={e => setPosition(Number(e.target.value))} aria-label="Drag to compare before and after"/></div><div className="before-after-caption"><span>01 / BEFORE & AFTER</span><span>DRAG TO EXPLORE <ArrowRight size={14}/></span></div></div></section>;
}

function ProjectArtwork({ src, alt, sizes, className, priority = false }: { src: string; alt: string; sizes: string; className?: string; priority?: boolean }) {
  const fallbackImages = [
    heroImage,
    detailImage,
    comparisonBefore,
  ];
  const imageSources = Array.from(new Set([src || fallbackImages[0], ...fallbackImages]));
  const [failure, setFailure] = useState({ src, attempts: 0 });
  const failedAttempts = failure.src === src ? failure.attempts : 0;
  const imageSrc = imageSources[Math.min(failedAttempts, imageSources.length - 1)];
  return <Image src={imageSrc} alt={alt} fill sizes={sizes} priority={priority} className={className} onError={event => { if (failedAttempts < imageSources.length - 1) setFailure({ src, attempts: failedAttempts + 1 }); else event.currentTarget.style.visibility = "hidden"; }}/>;
}

export default function HomeClient({ projects }: { projects: Project[] }) {
  const [filter, setFilter] = useState<Filter>("All Projects");
  const [quoteOpen, setQuoteOpen] = useState(false);
  const [selected, setSelected] = useState<Project | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 35); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  const visible = filter === "All Projects" ? projects : projects.filter(p => p.category === filter);
  function closeMenu() { setMenuOpen(false); }
  return <><div id="top" className="site-shell"><header className={`site-header ${scrolled ? "is-scrolled" : ""}`}><div className="header-inner"><Logo/><nav className="desktop-nav" aria-label="Main navigation"><a href="#about">About us</a><a href="#services">Expertise</a><a href="#projects">Projects</a><a href="#contact">Contact</a></nav><div className="header-right"><a className="header-whatsapp" href="https://wa.me/923161119482" target="_blank" rel="noreferrer" aria-label="Connect on WhatsApp"><MessageCircle size={18}/></a><button className="header-cta" onClick={() => setQuoteOpen(true)}>Let&apos;s talk <ArrowUpRight size={17}/></button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? <X/> : <Menu/>}</button></div></div></header><AnimatePresence>{menuOpen && <motion.nav className="mobile-nav" initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }}><a href="#about" onClick={closeMenu}>About us</a><a href="#services" onClick={closeMenu}>Expertise</a><a href="#projects" onClick={closeMenu}>Projects</a><a href="#contact" onClick={closeMenu}>Contact</a><button onClick={() => { closeMenu(); setQuoteOpen(true); }}>Request a quote <ArrowUpRight size={18}/></button><div className="mobile-nav-socials"><a href="https://www.facebook.com/profile.php?id=100091790475234" target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={14}/></a><a href="https://www.instagram.com/jauhar_decor/" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={14}/></a><a href="https://wa.me/923161119482" target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={14}/></a></div></motion.nav>}</AnimatePresence>

      <main><section className="hero" aria-label="Jauhar Decor introduction"><div className="hero-editorial"><div className="hero-copy-panel"><div className="hero-copy-inner"><motion.div className="hero-intro" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, delay: .1 }}><span className="hero-intro-line"/><span>GLASS · ALUMINUM · INTERIORS</span></motion.div><motion.h1 initial={{ opacity: 0, y: 35 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .9, delay: .25, ease: [0.22, 1, 0.36, 1] }}>Spaces,<br/>beautifully<br/><em>defined.</em></motion.h1><motion.div className="hero-description" initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .52 }}><p>Architectural glass and aluminum, considered down to the last detail. Made for the spaces you never want to leave.</p><div className="hero-actions"><a className="button button-light" href="#projects">Explore our work <ArrowUpRight size={18}/></a><button className="button button-outline" onClick={() => setQuoteOpen(true)}>Start a project <ArrowUpRight size={18}/></button></div></motion.div><div className="hero-copy-foot"><span>DESIGNED TO BE DIFFERENT</span><span>EST. JAUHAR DECOR <span className="hero-asterisk">✳</span></span></div></div></div><div className="hero-photo-panel"><motion.div className="hero-image-reveal" initial={{ clipPath: "inset(0 100% 0 0)" }} animate={{ clipPath: "inset(0 0% 0 0)" }} transition={{ duration: 1.25, delay: .18, ease: [0.76, 0, 0.24, 1] }}><Image src="/images/hero-editorial.jpg" alt="Sunlit contemporary residence with floor-to-ceiling architectural glass" fill priority sizes="(max-width: 800px) 100vw, 55vw" className="hero-image"/><div className="hero-photo-shade"/></motion.div><div className="hero-photo-top">THE ART OF LIVING WELL <span>— 01</span></div><div className="hero-photo-bottom"><div className="hero-photo-caption"><span>01 / THE ART OF SPACE</span><strong>Form follows feeling.</strong></div><a href="#about" aria-label="Scroll to discover" className="hero-scroll-circle"><ArrowDown size={22} strokeWidth={1.4}/></a></div></div></div><div className="hero-transition"><div className="hero-transition-inner"><span>01 — AN INTRODUCTION</span><span className="hero-transition-rule"/><span>PRECISION IN EVERY DETAIL</span><ArrowDown size={15}/></div></div></section>

      <section id="about" className="intro-section content-width"><div className="section-kicker"><span className="section-dot"/> ABOUT JAUHAR DECOR <span className="section-number">01 / 04</span></div><div className="intro-grid"><div><h2>Where vision<br/>meets <em>precision.</em></h2></div><div className="intro-right"><p>We shape the way you experience space. From a single pane of glass to an entire architectural facade, we bring thoughtful design, technical expertise, and exceptional craftsmanship to every detail.</p><a className="text-link" href="#services">DISCOVER OUR EXPERTISE <ArrowUpRight size={17}/></a></div></div><div className="metrics"><div><strong>100<span>%</span></strong><small>CUSTOM CRAFTED</small></div><div><strong>05<span>+</span></strong><small>SPECIALIZED SERVICES</small></div><div><strong>01</strong><small>STANDARD OF EXCELLENCE</small></div><div className="metric-statement">Built to elevate<br/><em>everyday living.</em></div></div></section>

      <section id="services" className="services-section"><div className="content-width"><div className="section-kicker"><span className="section-dot"/> OUR EXPERTISE <span className="section-number">02 / 04</span></div><div className="section-heading-row"><h2>Made for the way<br/>you <em>live & work.</em></h2><p>From first concept to final installation, we create architectural solutions that feel as good as they look.</p></div><div className="services-list">{services.map((service) => <div className="service-row" key={service.num}><span className="service-num">{service.num} /</span><span className="service-icon"><service.icon size={23} strokeWidth={1.3}/></span><div className="service-main"><h3>{service.title}</h3><p>{service.desc}</p></div><span className="service-arrow"><ArrowUpRight size={22} strokeWidth={1.3}/></span></div>)}</div></div></section>

      <section className="statement-section"><div className="statement-photo"><Image src="/images/project-studio.jpg" alt="Modern workspace with refined glass and aluminum details" fill sizes="(max-width: 800px) 100vw, 50vw" className="object-cover"/></div><div className="statement-content"><div className="statement-inner"><span className="eyebrow"><span className="section-dot"/> THE JAUHAR DIFFERENCE</span><h2>Every detail<br/>is a <em>decision.</em></h2><p>We believe the best spaces aren&apos;t just seen — they&apos;re felt. Our approach balances considered aesthetics with materials engineered to perform beautifully for years to come.</p><div className="statement-points"><span><Check size={15}/> Bespoke to your space</span><span><Check size={15}/> Precision fabrication</span><span><Check size={15}/> Enduring quality</span></div><button className="text-link" onClick={() => setQuoteOpen(true)}>START YOUR PROJECT <ArrowUpRight size={17}/></button></div></div></section>

      <section id="projects" className="projects-section content-width"><div className="section-kicker"><span className="section-dot"/> SELECTED WORK <span className="section-number">03 / 04</span></div><div className="section-heading-row projects-heading"><h2>Spaces that<br/><em>speak for themselves.</em></h2><p>A closer look at the ideas, materials and craftsmanship behind our work.</p></div><div className="project-toolbar"><div className="filters" role="group" aria-label="Filter projects">{filters.map(item => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "active" : ""}>{item === "All Projects" ? "All Projects" : categoryLabels[item]}</button>)}</div><span className="project-count">{String(visible.length).padStart(2, "0")} PROJECTS <ChevronDown size={15}/></span></div><div className="project-grid">{visible.map((project, i) => <motion.button layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: i * .05 }} key={project.id} className={`project-card ${filter === "All Projects" && i === 0 ? "project-card-featured" : ""}`} onClick={() => setSelected(project)}><div className="project-img"><ProjectArtwork src={project.coverImage} alt={project.title} sizes="(max-width: 700px) 100vw, (max-width: 1000px) 50vw, 60vw" className="object-cover"/><span className="project-view"><ArrowUpRight size={22}/></span></div><div className="project-info"><div><span>{categoryLabels[project.category as Category]} <span className="sep">/</span> {project.location || "Featured Project"}</span><h3>{project.title}</h3></div><span className="project-index">{String(i + 1).padStart(2, "0")}</span></div></motion.button>)}</div>{visible.length === 0 && <div className="empty-projects">No projects in this category yet. Explore another collection.</div>}</section>

      <BeforeAfterSlider/>

      <section className="quote-banner" id="contact"><div className="quote-banner-bg"/><div className="content-width quote-banner-inner"><div><span className="eyebrow"><span className="section-dot"/> YOUR VISION, OUR CRAFT</span><h2>Let&apos;s create<br/><em>something remarkable.</em></h2><p>Have a space in mind? Let&apos;s talk about how we can bring it to life.</p></div><button className="round-cta" onClick={() => setQuoteOpen(true)} aria-label="Request a quotation"><ArrowUpRight size={38} strokeWidth={1.2}/><span>GET IN TOUCH</span></button></div></section>
      </main><footer className="footer"><div className="content-width"><div className="footer-top"><div className="footer-brand"><Logo/><p>Crafting architectural glass, aluminum, and interiors for spaces worth experiencing.</p></div><div className="footer-links"><div><span>EXPLORE</span><a href="#about">About us</a><a href="#services">Our expertise</a><a href="#projects">Selected work</a><button onClick={() => setQuoteOpen(true)}>Get a quote</button></div><div><span>CONNECT</span><a href="https://www.instagram.com/jauhar_decor/" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={13}/></a><a href="https://www.facebook.com/profile.php?id=100091790475234" target="_blank" rel="noreferrer">Facebook <ArrowUpRight size={13}/></a><a href="https://wa.me/923161119482" target="_blank" rel="noreferrer">WhatsApp <ArrowUpRight size={13}/></a></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} JAUHAR DECOR. ALL RIGHTS RESERVED.</span><div><a href="https://www.instagram.com/jauhar_decor/" aria-label="Instagram" target="_blank" rel="noreferrer"><Camera size={18}/></a><a href="https://www.facebook.com/profile.php?id=100091790475234" aria-label="Facebook" target="_blank" rel="noreferrer"><Share2 size={18}/></a><a href="https://wa.me/923161119482" aria-label="WhatsApp" target="_blank" rel="noreferrer"><MessageCircle size={18}/></a></div><a href="#top">BACK TO TOP <ArrowUpRight size={15}/></a></div></div></footer></div><a className="whatsapp-float" href="https://wa.me/923161119482" target="_blank" rel="noreferrer" aria-label="Chat with Jauhar Decor on WhatsApp" title="Chat on WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 3.1A12.7 12.7 0 0 0 5.05 22.22L3.3 28.7l6.63-1.74A12.7 12.7 0 1 0 16 3.1Zm0 23.05a10.3 10.3 0 0 1-5.26-1.44l-.38-.23-3.92 1.03 1.05-3.81-.25-.4A10.28 10.28 0 1 1 16 26.15Z"/><path fill="currentColor" d="M22.03 18.62c-.33-.17-1.96-.97-2.26-1.08-.3-.11-.52-.17-.74.17-.22.33-.85 1.08-1.04 1.3-.19.22-.38.25-.71.08-.33-.17-1.39-.51-2.65-1.63-.98-.87-1.64-1.95-1.83-2.28-.19-.33-.02-.51.14-.67.15-.15.33-.39.49-.58.16-.19.22-.33.33-.55.11-.22.06-.41-.03-.58-.08-.17-.74-1.79-1.02-2.45-.27-.64-.55-.55-.74-.56-.19-.01-.41-.01-.63-.01-.22 0-.58.08-.88.41-.3.33-1.15 1.13-1.15 2.75 0 1.62 1.18 3.19 1.35 3.41.17.22 2.32 3.54 5.63 4.96.79.34 1.41.55 1.89.7.79.25 1.51.22 2.08.13.63-.09 1.96-.8 2.24-1.57.28-.77.28-1.43.19-1.57-.08-.14-.3-.22-.63-.39Z"/></svg></a><AnimatePresence>{quoteOpen && <QuoteModal onClose={() => setQuoteOpen(false)}/>}</AnimatePresence><AnimatePresence>{selected && <ProjectLightbox project={selected} onClose={() => setSelected(null)}/>}</AnimatePresence></>;
}
